functionsDirectory = "D:\\Redihire\\Redihire_Core\\project\\netlify\\functions"
functionsDirectoryOrigin = "config"
plugins = []
headers = []

[build]
publish = "D:\\Redihire\\Redihire_Core\\project\\dist"
publishOrigin = "ui"
commandOrigin = "ui"
command = "yarn run build"
functions = "D:\\Redihire\\Redihire_Core\\project\\netlify\\functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["nodemailer"]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false
