[build]
  command = "npm run build"
  publish = "build"  # or "dist" based on framework

[functions]
  directory = "netlify/functions"
  external_node_modules = ["nodemailer"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
