[build]
command = "tsc -p tsconfig.node.json"
publish = "dist"
functions = "netlify/functions"

[functions."*"]
external_node_modules = ["nodemailer"]
node_bundler = "esbuild"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
